# Generated by Django 5.1.7 on 2025-03-28 11:15

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("is_client", models.BooleanField(default=False)),
                ("is_expert", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.profile_picture_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_logout", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientRegistration",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="client_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Tell us about yourself"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Your primary location", max_length=100
                    ),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("both", "Both"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
                "ordering": ["user__created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertRegistration",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="expert_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expertise",
                    models.CharField(
                        help_text="Your primary area of expertise", max_length=120
                    ),
                ),
                ("bio", models.TextField(help_text="Detailed professional bio")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Your hourly rate in USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Years of professional experience",
                        null=True,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "license_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "degree_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "id_proof_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("documents_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_to", models.TimeField(blank=True, null=True)),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="List your specialties separated by commas",
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        default="English",
                        help_text="Languages you speak (comma separated)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Profile",
                "verbose_name_plural": "Expert Profiles",
                "ordering": ["-is_approved", "user__created_at"],
            },
        ),
    ]
