# Generated by Django 5.1.7 on 2025-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_client",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_expert",
        ),
        migrations.AlterField(
            model_name="expert",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
