# Generated by Django 5.1.7 on 2025-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_expert_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="expert",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
