# Generated by Django 5.1.7 on 2025-04-01 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_is_client_remove_user_is_expert_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpertDocument",
        ),
    ]
