# Generated by Django 5.1.7 on 2025-04-08 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_expert_experience_years_and_more"),
    ]

    operations = []
