# Generated by Django 5.1.7 on 2025-04-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("payments", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_link",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="scheduling.schedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("client", "schedule"), ("expert", "schedule")},
        ),
    ]
