# Generated by Django 5.1.7 on 2025-04-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="client",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="expert",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="chat_status",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="is_read",
        ),
        migrations.AddField(
            model_name="chat",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="sender",
            field=models.CharField(default="system_user", max_length=255),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Expert",
        ),
    ]
